import streamlit as st
import os
import subprocess
from plantuml import PlantUML

st.set_page_config(layout="wide", page_title="Architectural Demo")

st.title("Structurizr (C4) + PlantUML (Code) Demo")
st.markdown("""
This dashboard demonstrates the **Zoom-In** approach to architecture.
- **Level 1 (System)**: Context & Containers (C4 Model).
- **Level 2 (Code)**: Domain Classes (UML).
- **Level 3 (Source)**: Auto-generated Python Code.
""")

base_dir = os.path.dirname(os.path.abspath(__file__))
c4_file = os.path.join(base_dir, "c4_system.puml")
domain_file = os.path.join(base_dir, "domain_model.puml")
src_dir = os.path.join(base_dir, "src")

# Helper to render
def render_puml(path):
    pl = PlantUML(url='http://www.plantuml.com/plantuml/img/')
    try:
        data = pl.processes_file(path)
        return path.replace(".puml", ".png")
    except Exception as e:
        st.error(f"Error rendering {path}: {e}")
        return None

# Tabs
tab_system, tab_code, tab_source = st.tabs(["1. System Architecture (C4)", "2. Domain Model (UML)", "3. Source Code (Python)"])

with tab_system:
    st.header("System Context & Containers")
    st.caption("Defined in `c4_system.puml` using C4-PlantUML syntax.")
    if st.button("Render System Diagram"):
        img = render_puml(c4_file)
        if img and os.path.exists(img):
            st.image(img)
    elif os.path.exists(c4_file.replace(".puml", ".png")):
        st.image(c4_file.replace(".puml", ".png"))

with tab_code:
    st.header("Domain Class Model")
    st.caption("Defined in `domain_model.puml`. This mimics the actual code structure.")
    if st.button("Render Domain Model"):
        img = render_puml(domain_file)
        if img and os.path.exists(img):
            st.image(img)
    elif os.path.exists(domain_file.replace(".puml", ".png")):
        st.image(domain_file.replace(".puml", ".png"))

with tab_source:
    st.header("Auto-Generated Code")
    st.caption("Generated by `generate_src.py` from the Domain Model.")
    
    if st.button("Regenerate Source Code"):
        subprocess.run(["python", os.path.join(base_dir, "generate_src.py")])
        st.success("Code Regenerated!")
    
    if os.path.exists(src_dir):
        files = os.listdir(src_dir)
        selected_file = st.selectbox("View File", files)
        if selected_file:
            with open(os.path.join(src_dir, selected_file), 'r') as f:
                st.code(f.read(), language='python')
    else:
        st.warning("Source code not found. Click 'Regenerate Source Code'.")
